import test,{beforeEach}from'node:test';
import assert from'node:assert/strict';
import {addUser,backend,browserHeaders,cookieHeader,driver,resetBackend}from'./helpers/harness.js';
import {handle,invalidateAccessCache,respondToError}from'../src/server.js';
import {resetLoginThrottle}from'../src/auth.js';

const request=driver(handle,respondToError),CLIENT_A='a9000000-0000-4000-8000-000000000001',CLIENT_B='b9000000-0000-4000-8000-000000000001',CASE_A='a9000000-0000-4000-8000-000000000002',CASE_B='b9000000-0000-4000-8000-000000000002',DOC_A='a9000000-0000-4000-8000-000000000003',DOC_B='b9000000-0000-4000-8000-000000000003';let owner,staff;
async function signIn(email){const r=await request({method:'POST',path:'/api/v1/auth/login',headers:browserHeaders(),body:{email,password:'correct-horse-battery'}});assert.equal(r.status,200,r.raw);return cookieHeader(r.cookies)}

beforeEach(()=>{resetBackend();resetLoginThrottle();invalidateAccessCache();owner=addUser({email:'p9-owner@caseflow.test',roles:['owner']});staff=addUser({email:'p9-staff@caseflow.test',roles:['admin']});backend.tables.clients.push({id:CLIENT_A,legal_name:'Synthetic A'},{id:CLIENT_B,legal_name:'Synthetic B'});backend.tables.cases.push({id:CASE_A,client_id:CLIENT_A,client_name:'Synthetic A',case_type:'I-130',service_code:'I-130',status:'active'},{id:CASE_B,client_id:CLIENT_B,client_name:'Synthetic B',case_type:'I-485',service_code:'I-485',status:'active'});backend.tables.documents.push({id:DOC_A,case_id:CASE_A,client_id:CLIENT_A,file_name:'a.pdf',object_key:'cases/a/a.pdf',content_type:'application/pdf',archived_at:null},{id:DOC_B,case_id:CASE_B,client_id:CLIENT_B,file_name:'b.pdf',object_key:'cases/b/b.pdf',content_type:'application/pdf',archived_at:null})});

test('RFE evidence matrix accepts same-case documents and denies forged cross-case links',async()=>{const ownerCookie=await signIn(owner.email),staffCookie=await signIn(staff.email),ownerHeaders=browserHeaders({cookie:ownerCookie});assert.equal((await request({method:'PUT',path:'/api/v1/access/policies',headers:ownerHeaders,body:{subject_type:'user',subject_id:staff.id,scopes:{cases:'explicit_client',documents:'explicit_client'}}})).status,200);assert.equal((await request({method:'POST',path:'/api/v1/access/record-grants',headers:ownerHeaders,body:{subject_type:'user',subject_id:staff.id,resource_type:'client',resource_id:CLIENT_A,effect:'grant'}})).status,201);const headers=browserHeaders({cookie:staffCookie});const notice=await request({method:'POST',path:`/api/v1/cases/${CASE_A}/agency-requests`,headers,body:{request_type:'RFE',title:'Synthetic RFE',response_due_date:'2026-10-01'}});assert.equal(notice.status,201,notice.raw);const requirement=await request({method:'POST',path:`/api/v1/agency-requests/${notice.body.data.id}/requirements`,headers,body:{requirement_code:'ITEM-1',title:'Identity evidence'}});assert.equal(requirement.status,201,requirement.raw);const forged=await request({method:'POST',path:`/api/v1/evidence-requirements/${requirement.body.data.id}/documents`,headers,body:{document_id:DOC_B}});assert.equal(forged.status,409,forged.raw);assert.equal(backend.tables.evidence_links.length,0);const linked=await request({method:'POST',path:`/api/v1/evidence-requirements/${requirement.body.data.id}/documents`,headers,body:{document_id:DOC_A}});assert.equal(linked.status,201,linked.raw);assert.equal(backend.tables.evidence_links[0].case_id,CASE_A);assert.ok(backend.tables.audit_events.some(event=>event.action==='evidence_document_linked'));const foreign=await request({method:'POST',path:`/api/v1/cases/${CASE_B}/agency-requests`,headers,body:{request_type:'RFE',title:'Forged'}});assert.equal(foreign.status,404);});

