"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminStaffRow } from "@/lib/admin-control";
import type { CommissionRow, CommissionRuleRow } from "@/lib/commissions";

type Props={role:"admin"|"manager"|"staff";rules:CommissionRuleRow[];commissions:CommissionRow[];staff:AdminStaffRow[]};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
async function post(body:Record<string,unknown>){const res=await fetch("/api/staff/commissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>null);if(!res.ok||!data?.ok)throw new Error(data?.error?.message??`Commission operation failed (${res.status})`);return data;}

export function CommissionsBoard({role,rules,commissions,staff}:Props){
  const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
  const run=async(body:Record<string,unknown>,ok="Saved")=>{setBusy(true);setMessage(null);setError(null);try{await post(body);setMessage(ok);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Operation failed");}finally{setBusy(false)}};
  const totals=useMemo(()=>({eligible:commissions.filter(c=>c.status==="eligible").reduce((n,c)=>n+c.amount,0),approved:commissions.filter(c=>c.status==="approved").reduce((n,c)=>n+c.amount,0),paid:commissions.filter(c=>c.status==="paid").reduce((n,c)=>n+c.amount,0)}),[commissions]);
  return <div className="ops-page space-y-4">
    <header className="ops-hero"><div><p className="ops-kicker">CAREER GATE · COMMISSIONS</p><h1>{role==="staff"?"My Commissions":"Commission Engine"}</h1><p>Event-backed eligibility, approval and payment history.</p></div></header>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Eligible" value={money(totals.eligible)}/><Metric label="Approved" value={money(totals.approved)}/><Metric label="Paid" value={money(totals.paid)}/></div>
    {(message||error)&&<div className={`rounded-xl border p-3 text-sm ${error?"border-red-400/20 bg-red-400/[.06] text-red-300":"border-emerald-400/20 bg-emerald-400/[.06] text-emerald-300"}`}>{error??message}</div>}
    {role==="admin"&&<RuleAdmin rules={rules} busy={busy} onRun={run}/>} 
    {role==="admin"&&<Eligibility staff={staff} busy={busy} onRun={run}/>} 
    <CommissionList rows={commissions} role={role} busy={busy} onRun={run}/>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="staff-kpi rounded-2xl p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-500">{label}</p><strong className="mt-2 block text-2xl text-slate-100">{value}</strong></div>}

function RuleAdmin({rules,busy,onRun}:{rules:CommissionRuleRow[];busy:boolean;onRun:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
  const [v,setV]=useState({rule_key:"employment_completion",commission_type:"fixed",commission_value:"0",trigger_event:"client.completed",basis:"total_paid",approval_required:true,require_account_paid:true,require_no_open_tasks:false});
  return <section className="ops-glass-card"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Commission Rules</h2><p className="text-xs text-slate-500">Versioned rules. Draft first, then activate explicitly.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Rule Key"><input className="ops-input" value={v.rule_key} onChange={e=>setV({...v,rule_key:e.target.value})}/></Field><Field label="Type"><select className="ops-select" value={v.commission_type} onChange={e=>setV({...v,commission_type:e.target.value})}><option value="fixed">Fixed</option><option value="percent">Percent</option></select></Field><Field label="Value"><input className="ops-input" inputMode="decimal" value={v.commission_value} onChange={e=>setV({...v,commission_value:e.target.value})}/></Field><Field label="Trigger"><select className="ops-select" value={v.trigger_event} onChange={e=>setV({...v,trigger_event:e.target.value})}><option value="client.completed">Client Completed</option><option value="payment.satisfied">Payment Satisfied</option></select></Field><Field label="Basis"><select className="ops-select" value={v.basis} onChange={e=>setV({...v,basis:e.target.value})}><option value="total_paid">Total Paid</option><option value="total_charged">Total Charged</option></select></Field><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={v.require_account_paid} onChange={e=>setV({...v,require_account_paid:e.target.checked})}/>Require account paid</label><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={v.require_no_open_tasks} onChange={e=>setV({...v,require_no_open_tasks:e.target.checked})}/>Require no open tasks</label><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={v.approval_required} onChange={e=>setV({...v,approval_required:e.target.checked})}/>Approval required</label></div><button disabled={busy||!v.rule_key.trim()} className="ops-primary-button mt-4" onClick={()=>void onRun({operation:"create_rule",rule_key:v.rule_key,commission_type:v.commission_type,commission_value:Number(v.commission_value),trigger_event:v.trigger_event,basis:v.basis,approval_required:v.approval_required,conditions:{require_account_paid:v.require_account_paid,require_no_open_tasks:v.require_no_open_tasks},eligible_roles:["staff"],eligible_staff:[]},"Rule draft created")}>Create Rule Draft</button>
    <div className="mt-4 grid gap-2">{rules.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-white/[.06] p-3"><strong>{r.rule_key} · v{r.version}</strong><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase">{r.status}</span><span className="text-sm text-slate-400">{r.commission_type} {r.commission_type==="percent"?`${r.commission_value}%`:money(r.commission_value)} · {r.trigger_event}</span>{r.status==="draft"&&<button disabled={busy} className="ml-auto ops-primary-button" onClick={()=>void onRun({operation:"activate_rule",rule_id:r.id},"Rule activated")}>Activate</button>}</div>)}</div>
  </section>;
}

function Eligibility({staff,busy,onRun}:{staff:AdminStaffRow[];busy:boolean;onRun:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
  return <section className="ops-glass-card"><h2 className="text-lg font-semibold">Staff Eligibility</h2><div className="mt-3 grid gap-2 lg:grid-cols-2">{staff.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border border-white/[.06] p-3"><div><strong>{s.display_name}</strong><p className="text-xs text-slate-500">{s.staff_code??"—"} · {s.role} · {s.active?"ACTIVE":"INACTIVE"}</p></div><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" disabled={busy||!s.active} checked={s.commission_eligible} onChange={e=>void onRun({operation:"set_staff_eligibility",staff_id:s.id,eligible:e.target.checked},e.target.checked?"Commission eligibility enabled":"Commission eligibility disabled")}/>Eligible</label></div>)}</div></section>;
}

function CommissionList({rows,role,busy,onRun}:{rows:CommissionRow[];role:Props["role"];busy:boolean;onRun:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
  return <section className="ops-glass-card overflow-x-auto"><h2 className="mb-3 text-lg font-semibold">Commission Records</h2><table className="table min-w-[1100px]"><thead><tr><th>Client</th><th>Employee</th><th>Rule</th><th>Trigger</th><th>Basis</th><th>Amount</th><th>Status</th><th>Eligible</th><th>Paid</th><th>Actions</th></tr></thead><tbody>{rows.map(c=><CommissionRecord key={c.id} row={c} role={role} busy={busy} onRun={onRun}/>)}{!rows.length&&<tr><td colSpan={10} className="p-6 text-center text-slate-500">No commission records.</td></tr>}</tbody></table></section>;
}
function CommissionRecord({row,role,busy,onRun}:{row:CommissionRow;role:Props["role"];busy:boolean;onRun:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
  const [reference,setReference]=useState("");const [reason,setReason]=useState("");const manage=role!=="staff";
  return <tr><td><Link className="text-cyan-300" href={`/staff/client/${row.client_id}`}>{row.client_name}</Link><div className="text-[10px] text-slate-500">{row.client_ref}</div></td><td>{row.employee_name}<div className="text-[10px] text-slate-500">{row.staff_code??"—"}</div></td><td>{row.rule_key} v{row.rule_version}</td><td>{row.trigger_event}</td><td>{money(row.basis_amount)}</td><td><strong>{money(row.amount)}</strong></td><td className="capitalize">{row.status}</td><td>{row.eligible_at?new Date(row.eligible_at).toLocaleDateString():"—"}</td><td>{row.paid_at?new Date(row.paid_at).toLocaleDateString():"—"}</td><td>{manage&&<div className="flex min-w-72 flex-col gap-2">{row.status==="eligible"&&<button disabled={busy} className="ops-primary-button" onClick={()=>void onRun({operation:"approve_commission",commission_id:row.id},"Commission approved")}>Approve</button>}{["eligible","approved"].includes(row.status)&&<><input className="ops-input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Payment reference"/><button disabled={busy||!reference.trim()} className="ops-primary-button" onClick={()=>void onRun({operation:"mark_commission_paid",commission_id:row.id,payment_reference:reference},"Commission marked paid")}>Mark Paid</button></>}{!["paid","cancelled","reversed"].includes(row.status)&&<><input className="ops-input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Cancellation reason"/><button disabled={busy||!reason.trim()} className="rounded-xl border border-red-400/20 px-3 py-2 text-xs text-red-300" onClick={()=>void onRun({operation:"cancel_commission",commission_id:row.id,reason},"Commission cancelled")}>Cancel</button></>}</div>}</td></tr>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs text-slate-500"><span>{label}</span>{children}</label>}
