import Link from "next/link";
import type { StaffWorkspaceData } from "@/lib/workspace";

const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
function dueTone(value:string|null){if(!value)return "text-slate-500";const d=new Date(value).getTime();return d<Date.now()?"text-red-300":d<Date.now()+86400000?"text-amber-300":"text-slate-400"}

export function StaffWorkspace({data}:{data:StaffWorkspaceData}){
  const dueToday=data.tasks.filter(t=>t.due_at&&new Date(t.due_at).toDateString()===new Date().toDateString()).length;
  const overdue=data.tasks.filter(t=>t.due_at&&new Date(t.due_at).getTime()<Date.now()).length;
  const earned=data.commissions.filter(c=>c.status==="paid").reduce((n,c)=>n+c.amount,0);
  return <div className="ops-page space-y-5">
    <header className="ops-hero"><div><p className="ops-kicker">CAREER GATE · STAFF WORKSPACE</p><h1>My Work</h1><p>Today’s assigned clients, tasks, reviews, appointments, follow-ups and commissions.</p></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="My Clients" value={data.clients.length}/><Metric label="Due Today" value={dueToday}/><Metric label="Overdue" value={overdue} danger={overdue>0}/><Metric label="Reviews" value={data.reviews.length}/><Metric label="Appointments" value={data.appointments.length}/><Metric label="Paid Commissions" value={money(earned)}/></div>

    <section className="grid gap-4 xl:grid-cols-2">
      <Panel title="Do Now / My Tasks" empty="No open assigned tasks.">{data.tasks.map(t=><Link key={t.id} href={`/staff/client/${t.client_id}?tab=work`} className="block rounded-xl border border-white/[.06] p-3 hover:bg-white/[.025]"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm text-slate-200">{t.title}</strong><p className="mt-1 text-xs text-slate-500">{t.client_name} · {t.client_ref}</p></div><span className={`text-xs ${dueTone(t.due_at)}`}>{t.due_at?new Date(t.due_at).toLocaleString():"No due date"}</span></div></Link>)}</Panel>
      <Panel title="Review Queue" empty="No documents waiting for your clients.">{data.reviews.map(r=><Link key={r.id} href={`/staff/client/${r.client_id}?tab=documents`} className="block rounded-xl border border-white/[.06] p-3 hover:bg-white/[.025]"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm text-slate-200">{r.client_name}</strong><p className="mt-1 text-xs text-slate-500">{r.doc_type.replace(/_/g," ")} · {r.file_name}</p></div><span className="rounded-full border border-amber-400/20 px-2 py-1 text-[10px] capitalize text-amber-300">{r.status.replace(/_/g," ")}</span></div></Link>)}</Panel>
    </section>

    <section className="ops-glass-card overflow-x-auto"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-semibold">My Clients</h2><p className="text-sm text-slate-500">Next action is the operating priority.</p></div><Link href="/staff/clients" className="ops-primary-button">All Clients</Link></div><table className="table min-w-[1000px]"><thead><tr><th>Client</th><th>Status</th><th>Readiness</th><th>Next Action</th><th>Due / Waiting</th><th>Missing</th></tr></thead><tbody>{data.clients.map(c=><tr key={c.id}><td><Link className="text-cyan-300" href={`/staff/client/${c.id}`}>{c.full_name}</Link><div className="text-[10px] text-slate-500">{c.ref}</div></td><td className="capitalize">{c.current_status.replace(/_/g," ")}</td><td>{c.readiness_percent==null?"—":`${c.readiness_percent}%`}</td><td>{c.next_step}</td><td className={dueTone(c.next_action_due_at)}>{c.next_action_due_at?new Date(c.next_action_due_at).toLocaleString():c.waiting_condition??"—"}</td><td>{c.missing_count}</td></tr>)}</tbody></table></section>

    <section className="grid gap-4 xl:grid-cols-2">
      <Panel title="Upcoming Appointments" empty="No upcoming appointments.">{data.appointments.map(a=><Link key={a.id} href={`/staff/client/${a.client_id}?tab=appointments`} className="block rounded-xl border border-white/[.06] p-3 hover:bg-white/[.025]"><div className="flex justify-between gap-3"><div><strong className="text-sm text-slate-200">{a.client_name}</strong><p className="mt-1 text-xs text-slate-500">{a.appointment_type.replace(/_/g," ")} · {a.location??"Method not set"}</p></div><span className="text-xs text-slate-400">{new Date(a.scheduled_at).toLocaleString()}</span></div></Link>)}</Panel>
      <Panel title="Follow-Ups" empty="No open follow-ups.">{data.followups.map(f=><Link key={f.id} href={`/staff/client/${f.client_id}?tab=work`} className="block rounded-xl border border-white/[.06] p-3 hover:bg-white/[.025]"><div className="flex justify-between gap-3"><div><strong className="text-sm text-slate-200">{f.client_name}</strong><p className="mt-1 text-xs text-slate-500">{f.reason}</p></div><span className="text-xs text-slate-400">{f.due_date}</span></div></Link>)}</Panel>
    </section>

    <section className="ops-glass-card"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-semibold">My Commissions</h2><p className="text-sm text-slate-500">Read-only personal commission state.</p></div><Link href="/staff/commissions" className="ops-primary-button">Open Commissions</Link></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{data.commissions.slice(0,8).map(c=><Link href={`/staff/client/${c.client_id}`} key={c.id} className="rounded-xl border border-white/[.06] p-3"><span className="text-xs text-slate-500">{c.client_ref}</span><strong className="mt-1 block text-sm text-slate-200">{c.client_name}</strong><div className="mt-2 flex items-center justify-between"><b>{money(c.amount)}</b><span className="text-xs capitalize text-slate-400">{c.status}</span></div></Link>)}{!data.commissions.length&&<p className="text-sm text-slate-500">No commission records.</p>}</div></section>
  </div>;
}
function Metric({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <div className="staff-kpi rounded-2xl p-4"><p className="text-xs uppercase tracking-[.11em] text-slate-500">{label}</p><strong className={`mt-2 block text-2xl ${danger?"text-red-300":"text-slate-100"}`}>{value}</strong></div>}
function Panel({title,empty,children}:{title:string;empty:string;children:React.ReactNode}){const has=Array.isArray(children)?children.length>0:Boolean(children);return <section className="ops-glass-card"><h2 className="mb-3 text-xl font-semibold">{title}</h2><div className="grid gap-2">{has?children:<p className="text-sm text-slate-500">{empty}</p>}</div></section>}
