/**
 * Every word the client-facing intake page shows, in both languages.
 *
 * One page serves Arabic and English: there is no separate Arabic route. Arabic
 * is the default and renders right-to-left; English renders left-to-right.
 */

export type IntakeLocale = "ar" | "en";

export const INTAKE_COPY = {
  ar: {
    dir: "rtl" as const,
    brand: "بوابة التوظيف",
    office: "مكتب الهجرة للاستشارات وخدمات الهجرة والتوظيف",
    heading: "إدخال بيانات العميل",
    lead: "هذا الرابط مخصص لك لمرة واحدة. أكمل الخطوات التالية ثم اضغط إرسال.",
    sourceHeading: "أدخل بياناتك هنا",
    sourceHelper: "أدخل أو الصق معلوماتك كما هي، وسيقوم النظام بقراءتها وتنظيمها تلقائيًا.",
    sourcePlaceholder: "الاسم الكامل\nرقم الهاتف\nالبريد الإلكتروني\nتاريخ الميلاد\nالعنوان، المدينة، الولاية، الرمز البريدي",
    detectedHeading: "البيانات المستخرجة",
    detectedHelper: "راجع القيم التي قرأها النظام. يمكنك تعديل أي قيمة قبل الإرسال.",
    detectedEmpty: "ابدأ بإدخال بياناتك وستظهر هنا تلقائيًا.",
    uploadHeading: "ارفع الوثائق",
    uploadHelper: "ارفع صور أو ملفات الوثائق المطلوبة.",
    chooseFiles: "اختر ملفات",
    takePhoto: "التقاط صورة",
    uploadFormats: "PDF أو JPG أو PNG أو WEBP · حتى 10 ملفات · 10 ميجابايت لكل ملف",
    filesHeading: "الملفات المختارة",
    remove: "إزالة",
    submit: "إرسال",
    submitting: "جارٍ الإرسال...",
    submitHelper: "املأ البيانات، ارفع الوثائق، راجع البيانات المستخرجة، ثم اضغط إرسال.",
    successHeading: "تم استلام معلوماتك بنجاح",
    successClosed: "تم إغلاق هذا الرابط ولا يمكن استخدامه مرة أخرى.",
    closedHeading: "هذا الرابط مغلق",
    closedBody: "تم استخدام هذا الرابط أو انتهت صلاحيته. تواصل مع المكتب للحصول على رابط جديد.",
    invalidHeading: "رابط غير صالح",
    invalidBody: "تحقق من الرابط الذي استلمته، أو تواصل مع المكتب.",
    needSomething: "أدخل بياناتك أو ارفع وثيقة واحدة على الأقل.",
    fileTooLarge: "حجم الملف أكبر من الحد المسموح (10 ميجابايت).",
    tooManyFiles: "الحد الأقصى 10 ملفات.",
    totalTooLarge: "إجمالي حجم الملفات أكبر من الحد المسموح (25 ميجابايت).",
    unsupported: "نوع الملف غير مدعوم. المدعوم: PDF و JPG و PNG و WEBP.",
    genericError: "تعذر الإرسال. حاول مرة أخرى.",
    fields: {
      full_name: "الاسم الكامل",
      phone: "رقم الهاتف",
      email: "البريد الإلكتروني",
      date_of_birth: "تاريخ الميلاد",
      street: "العنوان",
      city: "المدينة",
      state: "الولاية",
      zip: "الرمز البريدي",
      preferred_language: "اللغة المفضلة",
      english_proficiency: "مستوى الإنجليزية",
    },
  },
  en: {
    dir: "ltr" as const,
    brand: "Career Gate",
    office: "Immigration Consulting, Immigration & Employment Services",
    heading: "Client Intake",
    lead: "This link is for you and can be used once. Complete the steps below, then press Submit.",
    sourceHeading: "Enter your details here",
    sourceHelper: "Enter or paste your information and the system will organize it automatically.",
    sourcePlaceholder: "Full name\nPhone number\nEmail address\nDate of birth\nStreet, city, state, ZIP",
    detectedHeading: "Detected information",
    detectedHelper: "Review what the system read. You can change any value before submitting.",
    detectedEmpty: "Start entering your details and they will appear here automatically.",
    uploadHeading: "Upload Documents",
    uploadHelper: "Upload photos or document files.",
    chooseFiles: "Choose Files",
    takePhoto: "Take Photo",
    uploadFormats: "PDF, JPG, PNG or WEBP · up to 10 files · 10 MB each",
    filesHeading: "Selected files",
    remove: "Remove",
    submit: "Submit",
    submitting: "Submitting…",
    submitHelper: "Enter your information, upload documents, review the detected data, then press Submit.",
    successHeading: "Your information was submitted successfully.",
    successClosed: "This link is now closed and cannot be used again.",
    closedHeading: "This link is closed",
    closedBody: "It has already been used or has expired. Contact the office for a new link.",
    invalidHeading: "Invalid link",
    invalidBody: "Check the link you received, or contact the office.",
    needSomething: "Enter your details or upload at least one document.",
    fileTooLarge: "That file is larger than the 10 MB limit.",
    tooManyFiles: "Up to 10 files.",
    totalTooLarge: "The files total more than the 25 MB limit.",
    unsupported: "That file type is not supported. Supported: PDF, JPG, PNG, WEBP.",
    genericError: "Your information could not be submitted. Please try again.",
    fields: {
      full_name: "Full name",
      phone: "Phone",
      email: "Email",
      date_of_birth: "Date of birth",
      street: "Street",
      city: "City",
      state: "State",
      zip: "ZIP",
      preferred_language: "Preferred language",
      english_proficiency: "English level",
    },
  },
} as const;

export type IntakeStrings = (typeof INTAKE_COPY)[IntakeLocale];
