"use client";

import { FileSearch, Lock, Sparkles } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Notice } from "@/components/ui/notice";
import { useToast } from "@/components/ui/toast";
import { api, ApiError } from "@/lib/api";
import { fmtTime, shortHash } from "@/lib/format";
import { cn } from "@/lib/utils";

type Anchor = {
  quote_anchor_id: string;
  segment_id: string;
  start_ms: number;
  end_ms: number;
  speaker: string;
  verbatim: string;
  review_state: string;
  risk_markers?: string[];
  notice?: string;
};

type SummaryRow = {
  id: string;
  transcript_revision_id: string;
  transcript_sha256: string;
  summary_revision: number;
  status: string;
  generated_at: string;
  generation_model: string;
  content: {
    material_statements: Anchor[];
    unresolved_disputed_matters: Anchor[];
    chronological_timeline: Anchor[];
    participants_speakers: { speaker_id: string; display_name: string }[];
    limitations: string;
    integrity_review_status: { transcript_revision: number; unresolved_count: number; critical_items_pending: number };
  };
};

/** On-demand, record-grounded summary. Generated by the server from the selected locked
 * revision only; every statement links back to its segment and timestamp. */
export function SummaryPanel({
  recordingId,
  revision,
  rtl,
  onSeek,
}: {
  recordingId: string;
  revision: { id: string; status: string; number: number };
  rtl: boolean;
  onSeek: (ms: number) => void;
}) {
  const toast = useToast();
  const [row, setRow] = useState<SummaryRow | null>(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const locked = revision.status === "locked";

  const load = useCallback(async () => {
    try {
      const r = await api<{ summary: SummaryRow }>(`/api/recordings/${recordingId}/summaries/neutral?revision_id=${revision.id}`);
      setRow(r.summary);
    } catch {
      setRow(null);
    }
  }, [recordingId, revision.id]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- fetch an existing summary for this revision
    void load();
  }, [load]);

  async function generate() {
    setBusy(true);
    setErr(null);
    try {
      const r = await api<{ summary: SummaryRow }>(`/api/recordings/${recordingId}/summaries`, {
        method: "POST",
        json: { summary_type: "neutral", revision_id: revision.id },
      });
      setRow(r.summary);
      toast(rtl ? "الملخص جاهز" : "Summary ready");
    } catch (e) {
      setErr(e instanceof ApiError ? e.message : "Error");
    } finally {
      setBusy(false);
    }
  }

  if (!row) {
    return (
      <div className="glass flex flex-col items-center gap-3 rounded-2xl px-5 py-8 text-center" data-testid="summary-empty">
        <span className="grid size-11 place-items-center rounded-xl border border-white/10 bg-white/[0.04] text-primary-text">
          {locked ? <Sparkles className="size-5" /> : <Lock className="size-5" />}
        </span>
        <p className="max-w-md text-sm text-fg-muted">
          {locked
            ? rtl
              ? "الملخص اختياري ويُنشأ عند الطلب من النسخة المقفلة فقط، وكل بند فيه مرتبط بموضعه في النص والتسجيل."
              : "The summary is optional and generated on demand from the locked revision only; every item links to its place in the transcript and audio."
            : rtl
              ? "اقفل النسخة أولاً — يُنشأ الملخص من النص القانوني المقفل فقط."
              : "Lock the revision first — summaries are generated from the locked canonical transcript only."}
        </p>
        {locked && (
          <Button size="sm" onClick={generate} disabled={busy} data-testid="summary-generate">
            <FileSearch /> {busy ? "…" : rtl ? "إنشاء الملخص" : "Generate summary"}
          </Button>
        )}
        {err && <Notice tone="danger" role="alert">{err}</Notice>}
      </div>
    );
  }

  const c = row.content;
  const items = c.material_statements.length ? c.material_statements : c.chronological_timeline.slice(0, 8);
  return (
    <div className="space-y-4 fade-in" data-testid="summary">
      <div className="glass rounded-2xl p-4 sm:p-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <div className="eyebrow">{rtl ? "ملخص مستند إلى السجل" : "Record-grounded summary"}</div>
            <h3 className="mt-1 text-[15px] font-semibold text-fg">{rtl ? "البنود الجوهرية" : "Material statements"}</h3>
          </div>
          <Badge tone={row.status === "locked" ? "ok" : "neutral"}>{row.status}</Badge>
        </div>
        <dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-fg-subtle sm:grid-cols-4" dir="ltr">
          <div><dt className="inline">rev </dt><dd className="inline text-fg-muted">r{c.integrity_review_status.transcript_revision}</dd></div>
          <div><dt className="inline">transcript </dt><dd className="inline font-mono text-fg-muted" title={row.transcript_sha256}>{shortHash(row.transcript_sha256)}</dd></div>
          <div><dt className="inline">model </dt><dd className="inline text-fg-muted">{row.generation_model}</dd></div>
          <div><dt className="inline">at </dt><dd className="inline text-fg-muted">{new Date(row.generated_at).toLocaleString()}</dd></div>
        </dl>
      </div>
      <ol className="space-y-2">
        {items.map((a) => (
          <li key={a.quote_anchor_id} className="glass rounded-xl p-3.5">
            <div className="mb-1 flex items-center gap-2 text-xs">
              <button className="font-mono text-primary-text hover:underline" dir="ltr" onClick={() => onSeek(a.start_ms)}>
                {fmtTime(a.start_ms)}
              </button>
              <bdi className="text-fg-subtle">{a.speaker}</bdi>
              {(a.risk_markers ?? []).slice(0, 3).map((r) => (
                <Badge key={r} tone="warn">{r}</Badge>
              ))}
            </div>
            <p className="bidi-auto text-[15px] leading-7 text-fg" dir="auto">{a.verbatim}</p>
          </li>
        ))}
      </ol>
      {c.unresolved_disputed_matters.length > 0 && (
        <div className="glass rounded-2xl !border-warn/35 p-4">
          <h4 className="mb-2 text-sm font-semibold text-fg">{rtl ? "مسائل غير محسومة — لا يُعتمد عليها" : "Unresolved — not relied upon"}</h4>
          {c.unresolved_disputed_matters.map((a) => (
            <button key={a.quote_anchor_id} className={cn("me-3 font-mono text-xs text-warn hover:underline")} dir="ltr" onClick={() => onSeek(a.start_ms)}>
              {fmtTime(a.start_ms)}
            </button>
          ))}
        </div>
      )}
      <p className="px-1 text-center text-xs text-fg-subtle" dir="ltr">{c.limitations}</p>
    </div>
  );
}
