import crypto from 'node:crypto';
import {PDFCheckBox,PDFDocument,PDFDropdown,PDFOptionList,PDFRadioGroup,PDFTextField,StandardFonts,rgb} from 'pdf-lib';

export const AI_TOOL_ALLOWLIST=Object.freeze(new Set(['get_case_summary','get_participants','get_form_answers','get_form_definition','get_documents','get_verified_fields','get_open_findings','compare_forms','run_rule_validation','get_deadlines','get_family_history','get_address_history','get_employment_history','get_travel_history','generate_review_report']));
export const OFFICE_DOCUMENT_TYPES=Object.freeze(new Set(['GENERAL_AUTHORIZATION_POA','CHILD_INTERNATIONAL_TRAVEL_CONSENT']));
const text=(v,m=500)=>String(v??'').trim().slice(0,m),sha256=v=>crypto.createHash('sha256').update(v).digest('hex');
const present=v=>v!==null&&v!==undefined&&!(typeof v==='string'&&!v.trim())&&!(Array.isArray(v)&&!v.length);

export function participantMatch(input,candidates=[]){const n={name:text(input.legal_name).toLowerCase().replace(/\s+/g,' '),dob:text(input.date_of_birth),a:text(input.a_number).replace(/\D/g,''),passport:text(input.passport_number).toUpperCase().replace(/\s/g,''),email:text(input.email).toLowerCase(),phone:text(input.phone).replace(/\D/g,'')};return candidates.map(c=>{const reasons=[],name=text(c.legal_name).toLowerCase().replace(/\s+/g,' ');if(n.a&&n.a===text(c.a_number).replace(/\D/g,''))reasons.push('A_NUMBER_EXACT');if(n.passport&&n.passport===text(c.passport_number).toUpperCase().replace(/\s/g,''))reasons.push('PASSPORT_EXACT');if(n.email&&n.email===text(c.email).toLowerCase())reasons.push('EMAIL_EXACT');if(n.phone&&n.phone===text(c.phone).replace(/\D/g,''))reasons.push('PHONE_EXACT');if(n.name&&n.name===name&&n.dob&&n.dob===text(c.date_of_birth))reasons.push('NAME_DOB_EXACT');return{person_id:c.id,legal_name:c.legal_name,reasons,possible_match:Boolean(reasons.length)}}).filter(x=>x.possible_match)}
export function routeAsylumAuthority(f={}){if(f.in_removal_proceedings===true||f.eoir_case_number)return{authority:'EOIR',form_code:'I-589',context:'EOIR_REMOVAL'};if(f.in_removal_proceedings===false&&f.seeking_affirmative_asylum===true)return{authority:'USCIS',form_code:'I-589',context:'USCIS_AFFIRMATIVE'};return{authority:null,form_code:'I-589',context:'REVIEW_REQUIRED',blocker:'ASYLUM_AUTHORITY_FACTS_REQUIRED'}}
export function routePassport(f={}){const age=Number(f.applicant_age);if(!Number.isFinite(age)||age<0)return{status:'REVIEW_REQUIRED',forms:[],blockers:['APPLICANT_AGE_REQUIRED']};if(f.lost_or_stolen===true)return{status:'ROUTED',forms:['DS-64','DS-11'],reason:'LOST_OR_STOLEN_REPLACEMENT'};if(f.data_correction===true||f.name_change_within_one_year===true||f.limited_validity_replacement===true)return{status:'ROUTED',forms:['DS-5504'],reason:'CORRECTION_OR_LIMITED_VALIDITY'};if(age<16)return{status:'ROUTED',forms:f.both_parents_appearing===false&&f.non_appearing_parent_can_consent===true?['DS-11','DS-3053']:['DS-11'],reason:'CHILD_UNDER_16'};const eligible=f.first_passport===false&&f.previous_passport_in_possession===true&&f.previous_passport_damaged!==true&&f.previous_passport_lost!==true&&f.previous_passport_issued_age>=16&&f.previous_passport_issued_within_15_years===true;return eligible?{status:'ROUTED',forms:['DS-82'],reason:'FACTS_SUPPORT_MAIL_RENEWAL'}:{status:'ROUTED',forms:['DS-11'],reason:f.first_passport===true?'FIRST_PASSPORT':'RENEWAL_FACTS_NOT_ESTABLISHED'}}
export function blankAudit(definition,answers={}){const findings=[];for(const field of definition?.fields||[]){const visible=typeof field.visible_when!=='object'||Object.entries(field.visible_when).every(([p,e])=>answers[p]===e),value=answers[field.path];if(!visible){if(present(value))findings.push({category:'CONDITIONAL_CONFLICT',severity:'review',field_path:field.path,claim:'A hidden field contains a value.'});continue}if(field.required&&!present(value))findings.push({category:'MISSING_DATA',severity:'blocker',field_path:field.path,claim:'Applicable required answer is missing.',blank_state:'missing_data'});if(!present(value)&&field.mapping_status==='unmapped')findings.push({category:'UNMAPPED',severity:'blocker',field_path:field.path,claim:'Applicable field has no official PDF mapping.',blank_state:'unmapped'})}return findings}
export function compareFormAnswers(instances=[]){const by=new Map(),out=[];for(const i of instances)for(const a of i.answers||[]){if(!a.canonical_field_path||!present(a.value))continue;const old=by.get(a.canonical_field_path),value=JSON.stringify(a.value);if(old&&old.value!==value)out.push({category:'CROSS_FORM_CONFLICT',severity:'blocker',field_path:a.canonical_field_path,claim:`${old.form_code} differs from ${i.form_code}.`,source_references:[old.answer_id,a.id].filter(Boolean)});else by.set(a.canonical_field_path,{value,form_code:i.form_code,answer_id:a.id})}return out}
export function validateDefinition(d){const errors=[];if(!d||!Array.isArray(d.fields)||!d.fields.length)errors.push('FIELDS_REQUIRED');const seen=new Set();for(const [i,f] of(d?.fields||[]).entries()){if(!f.path||!f.official_label||!f.part||!f.item_number)errors.push(`FIELD_${i+1}_OFFICIAL_STRUCTURE_REQUIRED`);if(seen.has(f.path))errors.push(`DUPLICATE_FIELD_PATH:${f.path}`);seen.add(f.path);if(!f.canonical_field_path)errors.push(`CANONICAL_PATH_REQUIRED:${f.path||i+1}`)}return{valid:!errors.length,errors}}
export function validateVersionActivation(v,d){const errors=[];if(!v?.official_pdf_source||!v?.source_sha256||!v?.verified_at)errors.push('OFFICIAL_SOURCE_NOT_VERIFIED');if(!v?.edition_date)errors.push('EDITION_REQUIRED');if(v?.mapping_test_status!=='passed')errors.push('MAPPING_HARNESS_NOT_PASSED');errors.push(...validateDefinition(d).errors);return{allowed:!errors.length,errors}}
export function formReadiness({definition,answers,version,crossFormFindings=[]}){const findings=[...blankAudit(definition,answers),...crossFormFindings],activation=validateVersionActivation(version,definition);for(const error of activation.errors)findings.push({category:'VERSION_CONTROL',severity:'blocker',claim:error});return{blockers:findings.filter(x=>x.severity==='blocker'),warnings:findings.filter(x=>x.severity==='warning'),review_items:findings.filter(x=>x.severity==='review'),ready_items:(definition?.fields||[]).filter(f=>present(answers[f.path])&&!findings.some(x=>x.field_path===f.path)),filing_ready:findings.every(x=>x.severity!=='blocker')}}
export function validateAiFinding(f){const required=['finding_id','category','severity','case_id','claim','source_references','reason','suggested_action','requires_owner_approval','timestamp','provider','model_version'],errors=required.filter(k=>f?.[k]===undefined||f?.[k]===null);if(!['blocker','warning','review'].includes(f?.severity))errors.push('INVALID_SEVERITY');if(!Array.isArray(f?.source_references))errors.push('SOURCE_REFERENCES_MUST_BE_ARRAY');if(f?.requires_owner_approval!==true)errors.push('OWNER_APPROVAL_REQUIRED');return{valid:!errors.length,errors}}
export function authorizeAiTool(name,principal,caseId){if(!AI_TOOL_ALLOWLIST.has(name))return{allowed:false,error:'AI_TOOL_NOT_ALLOWED'};if(!principal?.id||!caseId)return{allowed:false,error:'AI_CONTEXT_REQUIRED'};return{allowed:true}}
export async function inspectPdfCapabilities(bytes){const pdf=await PDFDocument.load(bytes,{ignoreEncryption:false});let fields=[];try{fields=pdf.getForm().getFields().map(f=>({name:f.getName(),type:f.constructor.name}))}catch{}return{acroform:Boolean(fields.length),xfa:false,static:!fields.length,field_count:fields.length,fields}}
function setPdfField(field,value){if(field instanceof PDFTextField)field.setText(String(value??''));else if(field instanceof PDFCheckBox)value?field.check():field.uncheck();else if(field instanceof PDFRadioGroup)field.select(String(value));else if(field instanceof PDFDropdown||field instanceof PDFOptionList)field.select(String(value));else throw new Error(`UNSUPPORTED_PDF_FIELD_TYPE:${field.constructor.name}`)}
export async function populateOfficialPdf({sourceBytes,mapping,canonicalData,flatten=false}){const pdf=await PDFDocument.load(sourceBytes,{ignoreEncryption:false}),form=pdf.getForm(),names=new Set(form.getFields().map(f=>f.getName())),missing=[],expected=new Map(),overflows=[];for(const map of mapping){if(!names.has(map.pdf_field)){missing.push(map.pdf_field);continue}const raw=canonicalData[map.canonical_field_path];if(raw===undefined)continue;const value=map.transform==='uppercase'?String(raw).toUpperCase():raw;if(typeof value==='string'&&map.max_length&&value.length>Number(map.max_length)){const o=map.overflow_rule;if(o?.type!=='additional_information'||!o.continuation_pdf_field||!o.reference_text)throw Object.assign(new Error('PDF_FIELD_OVERFLOW_REVIEW_REQUIRED'),{details:{field:map.pdf_field,length:value.length,max_length:Number(map.max_length)}});if(!names.has(o.continuation_pdf_field))throw new Error('PDF_CONTINUATION_FIELD_MISSING');setPdfField(form.getField(map.pdf_field),o.reference_text);setPdfField(form.getField(o.continuation_pdf_field),value);expected.set(map.pdf_field,o.reference_text);expected.set(o.continuation_pdf_field,value);overflows.push({field:map.pdf_field,continuation_field:o.continuation_pdf_field,reference:o.reference_text,review_required:true});continue}setPdfField(form.getField(map.pdf_field),value);expected.set(map.pdf_field,value)}if(missing.length)throw Object.assign(new Error('PDF_MAPPING_FIELDS_MISSING'),{details:{fields:missing}});form.updateFieldAppearances(await pdf.embedFont(StandardFonts.Helvetica));if(flatten)form.flatten();const bytes=await pdf.save({useObjectStreams:false}),reopened=await PDFDocument.load(bytes),rf=reopened.getForm(),mismatches=[];if(!flatten)for(const[name,value]of expected){const f=rf.getField(name);let actual;if(f instanceof PDFTextField)actual=f.getText();else if(f instanceof PDFCheckBox)actual=f.isChecked();else if(f instanceof PDFRadioGroup)actual=f.getSelected();else if(f instanceof PDFDropdown||f instanceof PDFOptionList)actual=f.getSelected();if(JSON.stringify(actual)!==JSON.stringify(value))mismatches.push(name)}if(mismatches.length)throw Object.assign(new Error('PDF_ROUND_TRIP_MISMATCH'),{details:{fields:mismatches}});return{bytes:Buffer.from(bytes),sha256:sha256(bytes),field_count:names.size,round_trip_passed:true,flattened:flatten,overflows}}
export async function generateControlledOfficeDocument({documentType,title,language='English',jurisdiction,purpose,sections=[]}){if(!OFFICE_DOCUMENT_TYPES.has(documentType))throw new Error('UNSUPPORTED_OFFICE_DOCUMENT_TYPE');if(!jurisdiction||!purpose)throw new Error('OFFICE_DOCUMENT_METADATA_REQUIRED');const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage([612,792]),y=740;const write=(v,size=11)=>{if(y<70){page=pdf.addPage([612,792]);y=740}page.drawText(String(v),{x:54,y,size,font,color:rgb(.05,.1,.18),maxWidth:504,lineHeight:size*1.35});y-=size*1.65};write(title,18);write(`${documentType} | ${jurisdiction} | ${language}`,9);write(`Purpose: ${purpose}`,10);y-=10;for(const s of sections){write(s.heading,13);for(const p of s.paragraphs||[])write(p,10);y-=6}const bytes=await pdf.save({useObjectStreams:false});return{bytes:Buffer.from(bytes),sha256:sha256(bytes),official:false,document_type:documentType}}
export function newJob({jobType,idempotencyKey,caseId,participantId,payload,requestedBy}){if(!jobType||!idempotencyKey)throw new Error('JOB_IDEMPOTENCY_REQUIRED');return{id:crypto.randomUUID(),job_type:jobType,idempotency_key:idempotencyKey,case_id:caseId||null,participant_id:participantId||null,status:'queued',progress:0,payload:payload||{},requested_by:requestedBy}}
