import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
const port=Number(process.env.PORT||3000),version='2.0.0',service='alhijrah-caseflow-api';
const supabaseUrl=process.env.SUPABASE_URL?.replace(/\/$/,''),supabaseServiceKey=process.env.SUPABASE_SERVICE_ROLE_KEY,internalApiKey=process.env.INTERNAL_API_KEY,r2Bucket=process.env.R2_BUCKET,r2Endpoint=process.env.R2_ENDPOINT||(process.env.R2_ACCOUNT_ID?`https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`:undefined);
const r2=r2Endpoint&&process.env.R2_ACCESS_KEY_ID&&process.env.R2_SECRET_ACCESS_KEY?new S3Client({region:'auto',endpoint:r2Endpoint,credentials:{accessKeyId:process.env.R2_ACCESS_KEY_ID,secretAccessKey:process.env.R2_SECRET_ACCESS_KEY}}):null;
function headers(){return {'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','strict-transport-security':'max-age=31536000; includeSubDomains'}}function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8',...headers()});res.end(JSON.stringify(body))}async function readJson(req){const c=[];for await(const x of req)c.push(x);try{return JSON.parse(Buffer.concat(c).toString('utf8')||'{}')}catch{throw Object.assign(new Error('INVALID_JSON'),{status:400})}}function auth(req){if(!internalApiKey)throw Object.assign(new Error('API_NOT_CONFIGURED'),{status:503});const s=req.headers['x-api-key'];if(typeof s!=='string'||s!==internalApiKey)throw Object.assign(new Error('UNAUTHORIZED'),{status:401})}async function db(path,{method='GET',body,query=''}={}){if(!supabaseUrl||!supabaseServiceKey)throw Object.assign(new Error('SUPABASE_NOT_CONFIGURED'),{status:503});const r=await fetch(`${supabaseUrl}/rest/v1/${path}${query}`,{method,headers:{apikey:supabaseServiceKey,authorization:`Bearer ${supabaseServiceKey}`,'content-type':'application/json',prefer:method==='POST'||method==='PATCH'?'return=representation':''},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Object.assign(new Error('DATABASE_REQUEST_FAILED'),{status:r.status>=500?502:r.status,details:d});return d}function safe(x){const c=String(x||'').replace(/[^a-zA-Z0-9._/-]/g,'_').replace(/\.\./g,'_');if(!c||c.startsWith('/'))throw Object.assign(new Error('INVALID_OBJECT_KEY'),{status:400});return c}
async function handle(req,res){const id=crypto.randomUUID(),u=new URL(req.url,`http://${req.headers.host||'localhost'}`);res.setHeader('x-request-id',id);if(req.method==='GET'&&u.pathname==='/'){const html=fs.readFileSync(new URL('./public/index.html',import.meta.url));res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache','x-content-type-options':'nosniff'});return res.end(html)}if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{status:'ok',service,version,requestId:id});if(req.method==='GET'&&u.pathname==='/ready'){const checks={supabase:Boolean(supabaseUrl&&supabaseServiceKey),r2:Boolean(r2&&r2Bucket),internalAuth:Boolean(internalApiKey)},ready=Object.values(checks).every(Boolean);return json(res,ready?200:503,{status:ready?'ready':'not-ready',service,version,checks,requestId:id})}if(u.pathname.startsWith('/api/'))auth(req);if(req.method==='GET'&&u.pathname==='/api/v1/cases'){const data=await db('cases',{query:'?select=*&order=created_at.desc&limit=100'});return json(res,200,{data,requestId:id})}if(req.method==='POST'&&u.pathname==='/api/v1/cases'){const b=await readJson(req);if(!b.client_name||!b.case_type)throw Object.assign(new Error('client_name_and_case_type_required'),{status:400});const data=await db('cases',{method:'POST',body:{id:crypto.randomUUID(),client_name:String(b.client_name).trim(),case_type:String(b.case_type).trim(),status:String(b.status||'intake'),priority:String(b.priority||'normal'),assigned_to:b.assigned_to||null,notes:b.notes||null}});return json(res,201,{data,requestId:id})}if(req.method==='POST'&&u.pathname==='/api/v1/documents/presign'){if(!r2||!r2Bucket)throw Object.assign(new Error('R2_NOT_CONFIGURED'),{status:503});const b=await readJson(req),fn=safe(b.filename||'document.bin').split('/').pop(),key=safe(`cases/${b.case_id||'unassigned'}/${crypto.randomUUID()}-${fn}`),upload_url=await getSignedUrl(r2,new PutObjectCommand({Bucket:r2Bucket,Key:key,ContentType:String(b.content_type||'application/octet-stream')}),{expiresIn:900});return json(res,200,{key,upload_url,expires_in:900,requestId:id})}return json(res,404,{error:'NOT_FOUND',requestId:id})}
const server=http.createServer((req,res)=>handle(req,res).catch(e=>json(res,Number(e.status||500),{error:e.message||'INTERNAL_ERROR'})));server.requestTimeout=30000;server.headersTimeout=35000;server.listen(port,'0.0.0.0',()=>console.log(`Alhijrah Caseflow ${version} listening on ${port}`));
