begin;

alter table public.people add column if not exists legal_name_ar text;
alter table public.people add column if not exists current_country text;
alter table public.people add column if not exists whatsapp text;
alter table public.people add column if not exists preferred_language text not null default 'English';
alter table public.people add column if not exists uscis_account_number text;
alter table public.people add column if not exists passport_number text;
alter table public.people add column if not exists passport_country text;
alter table public.people add column if not exists passport_expiration date;
alter table public.people add column if not exists physical_address text;
alter table public.people add column if not exists postal_code text;
alter table public.people add column if not exists immigration_status text;
alter table public.people add column if not exists photo_object_key text;
alter table public.people add column if not exists identity_verification_status text not null default 'unverified';
alter table public.people add column if not exists identity_verified_at timestamptz;
alter table public.people add column if not exists identity_verified_by uuid;
alter table public.people add column if not exists archived_at timestamptz;

create table if not exists public.person_history_records(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.people(id) on delete restrict,case_id uuid references public.cases(id) on delete restrict,history_type text not null check(history_type in('immigration','address','employment','travel')),starts_on date,ends_on date,current_record boolean not null default false,details jsonb not null default '{}'::jsonb,verification_status text not null default'unverified' check(verification_status in('unverified','review_required','verified','rejected')),source_document_id uuid references public.documents(id) on delete set null,revision integer not null default 1 check(revision>0),created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,check(ends_on is null or starts_on is null or ends_on>=starts_on));
create table if not exists public.family_relationships(id uuid primary key default gen_random_uuid(),client_id uuid not null references public.clients(id) on delete restrict,person_id uuid not null references public.people(id) on delete restrict,related_person_id uuid not null references public.people(id) on delete restrict,relationship_type text not null check(relationship_type in('spouse','child','parent','sibling','guardian','other')),starts_on date,ends_on date,verification_status text not null default'unverified',created_by uuid,created_at timestamptz not null default now(),archived_at timestamptz,check(person_id<>related_person_id),check(ends_on is null or starts_on is null or ends_on>=starts_on));
create unique index if not exists family_relationships_active_unique_idx on public.family_relationships(client_id,person_id,related_person_id,relationship_type) where archived_at is null;
create table if not exists public.participant_match_reviews(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.cases(id) on delete restrict,proposed_data jsonb not null,matched_person_id uuid references public.people(id) on delete restrict,match_reasons jsonb not null default'[]'::jsonb,status text not null default'pending' check(status in('pending','link_existing','create_new','dismissed')),resolved_by uuid,resolved_at timestamptz,created_by uuid,created_at timestamptz not null default now());

create table if not exists public.form_registry(id uuid primary key default gen_random_uuid(),authority text not null check(authority in('USCIS','EOIR','DOS_PASSPORT','OFFICE')),form_code text not null,display_name text not null,official_form_page text,routing_context text,source_status text not null default'detected' check(source_status in('detected','verified','retired','review_required')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(authority,form_code));
create table if not exists public.form_versions(id uuid primary key default gen_random_uuid(),registry_id uuid not null references public.form_registry(id) on delete restrict,edition_date text not null,official_pdf_source text,official_instructions_source text,source_object_key text,retrieved_at timestamptz,verified_at timestamptz,source_etag text,source_last_modified text,source_sha256 text,instructions_sha256 text,pdf_capabilities jsonb not null default'{}'::jsonb,status text not null default'detected' check(status in('detected','retrieved','verified_source','hashed','diff_analyzed','mapped','tested','active','superseded','failed')),mapping_version integer,mapping_test_status text not null default'not_run' check(mapping_test_status in('not_run','failed','passed')),activated_by uuid,activated_at timestamptz,created_at timestamptz not null default now(),unique(registry_id,edition_date));
create unique index if not exists form_versions_one_active_idx on public.form_versions(registry_id) where status='active';
create table if not exists public.form_definitions(id uuid primary key default gen_random_uuid(),form_version_id uuid not null references public.form_versions(id) on delete restrict,mapping_version integer not null check(mapping_version>0),definition jsonb not null,definition_sha256 text not null,status text not null default'draft' check(status in('draft','review','tested','active','superseded')),created_by uuid,created_at timestamptz not null default now(),unique(form_version_id,mapping_version));
create table if not exists public.form_instances(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.cases(id) on delete restrict,participant_id uuid references public.people(id) on delete restrict,form_version_id uuid not null references public.form_versions(id) on delete restrict,form_definition_id uuid not null references public.form_definitions(id) on delete restrict,pinned_authority text,pinned_form_code text,pinned_edition_date text,pinned_mapping_version integer,pinned_source_sha256 text,status text not null default'draft' check(status in('draft','review_required','reviewed','final')),current_part text,revision integer not null default 1 check(revision>0),canonical_snapshot_hash text,created_by uuid,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists form_instances_participant_unique_idx on public.form_instances(case_id,participant_id,form_version_id) where participant_id is not null;
create unique index if not exists form_instances_case_unique_idx on public.form_instances(case_id,form_version_id) where participant_id is null;
create table if not exists public.form_rules(id uuid primary key default gen_random_uuid(),authority text not null,rule_code text not null,rule_version integer not null check(rule_version>0),official_source text not null,source_version_date text,verified_at timestamptz,status text not null default'unverified' check(status in('unverified','review_required','active','superseded')),rule_definition jsonb not null,created_by uuid,created_at timestamptz not null default now(),unique(authority,rule_code,rule_version));
create table if not exists public.form_answers(id uuid primary key default gen_random_uuid(),form_instance_id uuid not null references public.form_instances(id) on delete restrict,field_path text not null,answer_value jsonb,blank_state text check(blank_state in('not_applicable','intentionally_blank','missing_data','conditionally_hidden','unmapped','system_error')),source_type text not null default'manual' check(source_type in('manual','client','participant','history','document_ocr','verified_field','prior_form','system')),source_record_id uuid,source_document_id uuid references public.documents(id) on delete set null,verification_status text not null default'unverified' check(verification_status in('unverified','review_required','verified','rejected')),revision integer not null default 1 check(revision>0),last_changed_by uuid,last_changed_source text not null default'STAFF_ASSISTED' check(last_changed_source in('STAFF_ASSISTED','CLIENT_PORTAL','SYSTEM','IMPORT')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(form_instance_id,field_path));
create table if not exists public.form_findings(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.cases(id) on delete restrict,form_instance_id uuid references public.form_instances(id) on delete restrict,participant_id uuid references public.people(id) on delete restrict,category text not null,severity text not null check(severity in('blocker','warning','review','ready')),field_path text,claim text not null,source_references jsonb not null default'[]'::jsonb,rule_source jsonb,status text not null default'open' check(status in('open','accepted','resolved','dismissed')),created_by_type text not null default'deterministic' check(created_by_type in('deterministic','ai','human')),resolved_by uuid,resolved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.background_jobs(id uuid primary key default gen_random_uuid(),job_type text not null,idempotency_key text not null unique,case_id uuid references public.cases(id) on delete restrict,participant_id uuid references public.people(id) on delete restrict,status text not null default'queued' check(status in('queued','running','succeeded','failed','retrying','canceled')),progress integer not null default 0 check(progress between 0 and 100),payload jsonb not null default'{}'::jsonb,result jsonb,attempt_count integer not null default 0,last_error_code text,requested_by uuid,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.generated_artifacts(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.cases(id) on delete restrict,form_instance_id uuid references public.form_instances(id) on delete restrict,artifact_type text not null check(artifact_type in('official_form_pdf','office_document_pdf','review_report')),authority text not null,form_code text not null,edition_date text,mapping_version integer,source_artifact_hash text,object_key text not null,pdf_sha256 text not null,review_state text not null default'draft' check(review_state in('draft','review_required','reviewed','final')),immutable boolean not null default true,generated_by uuid,generated_at timestamptz not null default now(),unique(case_id,object_key));
create table if not exists public.ai_review_runs(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.cases(id) on delete restrict,provider text,model_version text,workflow_version text not null,status text not null default'queued' check(status in('queued','running','succeeded','failed','review_required')),requested_by uuid,approved_by uuid,started_at timestamptz,completed_at timestamptz,failure_code text,created_at timestamptz not null default now());
create table if not exists public.ai_findings(id uuid primary key default gen_random_uuid(),review_run_id uuid not null references public.ai_review_runs(id) on delete restrict,case_id uuid not null references public.cases(id) on delete restrict,participant_id uuid references public.people(id) on delete restrict,form_instance_id uuid references public.form_instances(id) on delete restrict,category text not null,severity text not null check(severity in('blocker','warning','review')),field_path text,claim text not null,source_references jsonb not null,reason text not null,suggested_action text not null,confidence text,requires_owner_approval boolean not null default true,resolution text check(resolution in('accepted','rejected','resolved')),resolved_by uuid,resolved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.controlled_document_templates(id uuid primary key default gen_random_uuid(),document_type text not null check(document_type in('GENERAL_AUTHORIZATION_POA','CHILD_INTERNATIONAL_TRAVEL_CONSENT')),jurisdiction text not null,purpose text not null,template_version integer not null check(template_version>0),language text not null check(language in('English','Arabic','Bilingual')),template_definition jsonb not null,source_review_status text not null default'review_required' check(source_review_status in('review_required','verified','superseded')),effective_date date,active boolean not null default false,created_by uuid,created_at timestamptz not null default now(),unique(document_type,jurisdiction,template_version,language));
create table if not exists public.form_update_alerts(id uuid primary key default gen_random_uuid(),form_version_id uuid not null references public.form_versions(id) on delete restrict,authority text not null,form_code text not null,old_source_sha256 text,detected_source_sha256 text,old_etag text,detected_etag text,official_source text not null,detected_at timestamptz not null default now(),affected_open_cases integer not null default 0 check(affected_open_cases>=0),mapping_status text not null default'review_required',status text not null default'open' check(status in('open','acknowledged','resolved','dismissed')),metadata jsonb not null default'{}'::jsonb);

create index if not exists person_history_person_idx on public.person_history_records(person_id,history_type,starts_on desc) where archived_at is null;
create index if not exists form_instances_case_idx on public.form_instances(case_id,status,updated_at desc);
create index if not exists form_findings_case_idx on public.form_findings(case_id,status,severity);
create index if not exists background_jobs_case_idx on public.background_jobs(case_id,status,created_at desc);
create index if not exists generated_artifacts_case_idx on public.generated_artifacts(case_id,generated_at desc);
create unique index if not exists form_update_alert_open_unique_idx on public.form_update_alerts(form_version_id,detected_source_sha256) where status in('open','acknowledged');

do $$ begin if not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='protect_form_instance_pin') then execute $f$create function public.protect_form_instance_pin() returns trigger language plpgsql as $b$ begin if old.pinned_authority is distinct from new.pinned_authority or old.pinned_form_code is distinct from new.pinned_form_code or old.pinned_edition_date is distinct from new.pinned_edition_date or old.pinned_mapping_version is distinct from new.pinned_mapping_version or old.pinned_source_sha256 is distinct from new.pinned_source_sha256 then raise exception 'Form edition pin is immutable'; end if; return new; end; $b$$f$;end if;end;$$;
do $$ begin if not exists(select 1 from pg_trigger where tgname='protect_form_instance_pin_trigger' and tgrelid='public.form_instances'::regclass)then create trigger protect_form_instance_pin_trigger before update on public.form_instances for each row execute function public.protect_form_instance_pin();end if;end;$$;

insert into public.form_registry(authority,form_code,display_name,official_form_page,routing_context) values
('USCIS','I-130','Petition for Alien Relative','https://www.uscis.gov/i-130','USCIS'),('USCIS','I-130A','Supplemental Information for Spouse Beneficiary','https://www.uscis.gov/i-130','USCIS'),('USCIS','I-485','Application to Register Permanent Residence or Adjust Status','https://www.uscis.gov/i-485','USCIS'),('USCIS','I-765','Application for Employment Authorization','https://www.uscis.gov/i-765','USCIS'),('USCIS','I-131','Application for Travel Documents','https://www.uscis.gov/i-131','USCIS'),('USCIS','I-864','Affidavit of Support','https://www.uscis.gov/i-864','USCIS'),('USCIS','I-864A','Contract Between Sponsor and Household Member','https://www.uscis.gov/i-864a','USCIS'),('USCIS','I-693','Medical Examination and Vaccination Record','https://www.uscis.gov/i-693','USCIS_CHECKLIST_ONLY'),('USCIS','I-751','Petition to Remove Conditions','https://www.uscis.gov/i-751','USCIS'),('USCIS','N-400','Application for Naturalization','https://www.uscis.gov/n-400','USCIS'),('USCIS','I-912','Request for Fee Waiver','https://www.uscis.gov/i-912','USCIS_INDEPENDENT'),('USCIS','I-589','Application for Asylum and Withholding','https://www.uscis.gov/i-589','USCIS_AFFIRMATIVE'),('EOIR','I-589','Application for Asylum and Withholding','https://www.justice.gov/eoir/reference-materials/ic/chapter-3/15','EOIR_REMOVAL'),('USCIS','I-601','Waiver of Grounds of Inadmissibility','https://www.uscis.gov/i-601','USCIS'),('USCIS','I-601A','Provisional Unlawful Presence Waiver','https://www.uscis.gov/i-601a','USCIS'),('USCIS','I-918','Petition for U Nonimmigrant Status','https://www.uscis.gov/i-918','USCIS'),('USCIS','I-918A','Qualifying Family Member of U-1','https://www.uscis.gov/i-918','USCIS'),('USCIS','I-914','Application for T Nonimmigrant Status','https://www.uscis.gov/i-914','USCIS'),('USCIS','I-914A','Family Member of T-1','https://www.uscis.gov/i-914','USCIS'),('USCIS','I-360','Petition for Special Immigrant','https://www.uscis.gov/i-360','USCIS'),('USCIS','G-28','Notice of Entry of Appearance as Attorney or Accredited Representative','https://www.uscis.gov/g-28','USCIS_APPEARANCE_ONLY'),('DOS_PASSPORT','DS-11','Application for a U.S. Passport','https://travel.state.gov/en/passports/apply/help/forms.html','PASSPORT'),('DOS_PASSPORT','DS-82','U.S. Passport Renewal Application','https://travel.state.gov/en/passports/apply/help/forms.html','PASSPORT'),('DOS_PASSPORT','DS-5504','Passport Name Change or Correction','https://travel.state.gov/en/passports/renew-replace/change-correct-passport.html','PASSPORT'),('DOS_PASSPORT','DS-64','Lost or Stolen Passport Statement','https://travel.state.gov/en/passports/renew-replace/lost-stolen.html','PASSPORT'),('DOS_PASSPORT','DS-3053','Consent for Passport to a Child','https://travel.state.gov/en/passports/need-passport/under-16.html','PASSPORT') on conflict(authority,form_code)do nothing;
insert into public.role_permissions(role_code,permission_code)values('admin','cases.prepare'),('supervisor','cases.prepare'),('case_manager','cases.prepare'),('attorney_accredited_representative','cases.prepare')on conflict(role_code,permission_code)do nothing;

do $$ declare t text;p text;begin foreach t in array array['person_history_records','family_relationships','participant_match_reviews','form_registry','form_versions','form_definitions','form_instances','form_rules','form_answers','form_findings','background_jobs','generated_artifacts','ai_review_runs','ai_findings','controlled_document_templates','form_update_alerts']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('revoke all on public.%I from anon, authenticated',t);execute format('grant select, insert, update on public.%I to service_role',t);p:=t||'_server_only';if not exists(select 1 from pg_policies where schemaname='public' and tablename=t and policyname=p)then execute format('create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',p,t);end if;end loop;end;$$;
notify pgrst,'reload schema';
commit;
